common/models/NSectionLink.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "n_section_link".
 *
 * @property int $id_section_link
 * @property int $id_section
 * @property int $id_link
 *
 * @property NLink $link
 * @property NSection $section
 */
class NSectionLink extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'n_section_link';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_section', 'id_link'], 'default', 'value' => null],
            [['id_section', 'id_link'], 'integer'],
            [['id_link'], 'exist', 'skipOnError' => true, 'targetClass' => NLink::className(), 'targetAttribute' => ['id_link' => 'id_link']],
            [['id_section'], 'exist', 'skipOnError' => true, 'targetClass' => NSection::className(), 'targetAttribute' => ['id_section' => 'id_section']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_section_link' => 'Код ссылки раздела',
            'id_section' => 'Код раздела',
            'id_link' => 'Код ссылки',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLink()
    {
        return $this->hasOne(NLink::className(), ['id_link' => 'id_link']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSection()
    {
        return $this->hasOne(NSection::className(), ['id_section' => 'id_section']);
    }

    /**
     * {@inheritdoc}
     * @return NSectionLinkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new NSectionLinkQuery(get_called_class());
    }
}

backend/controllers/NSectionLinkController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\NSectionLink;
use common\models\NSectionLinkSearch;
use common\models\NLinkSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * NSectionLinkController implements the CRUD actions for NSectionLink model.
 */
class NsectionlinkController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    // Здесь запрет перехода на страницу не автоизованному пользователю. 
                    [
                        'allow' => false,
                        'roles' => ['?']
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all NSectionLink models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NSectionLinkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single NSectionLink model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new NSectionLink model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NSectionLink();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_section_link]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing NSectionLink model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $searchModelNLink = new NLinkSearch();
        $dataProviderNLink = $searchModelNLink->search(Yii::$app->request->queryParams+['NLinkSearch' => ['==', 'id_link' =>$id]]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_section_link]);
        }

        return $this->render('update', [
            'model' => $model,
            'dataProviderNLink' => $dataProviderNLink,
        ]);
    }

    /**
     * Deletes an existing NSectionLink model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the NSectionLink model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NSectionLink the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NSectionLink::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/nsectionlink/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionLink */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nsection-link-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_section')->textInput() ?>

    <?= $form->field($model, 'id_link')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>


 <!--  --------------- Ссылки -------------- -->

    <?= ListView::widget([
            'dataProvider' => $dataProviderNLink,
            'summary' => false,
            'itemView'=> function ($model , $key , $index , $widget) {
                return $this->render('/nlink/update',[
                'model' => $model,
                ]);
            }
    ]) ?>    

</div>

backend/views/nsectionlink/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionLinkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nsection-link-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id_section_link') ?>

    <?= $form->field($model, 'id_section') ?>

    <?= $form->field($model, 'id_link') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/nsectionlink/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionLink */

$this->title = 'Добавить ссылки разделов';
$this->params['breadcrumbs'][] = ['label' => 'Nsection Links', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nsection-link-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/nsectionlink/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\NSectionLinkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ссылки разделов';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nsection-link-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('добавить ссылки разделов', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_section_link',
            'id_section',
            'id_link',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/nsectionlink/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionLink */

$this->title = 'Редактировать ссылки разделов: ' . $model->id_section_link;
$this->params['breadcrumbs'][] = ['label' => 'Ссылки разделов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_section_link, 'url' => ['view', 'id' => $model->id_section_link]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="nsection-link-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'dataProviderNLink' => $dataProviderNLink,
    ]) ?>

</div>

backend/views/nsectionlink/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionLink */

$this->title = 'Ссылка №' . $model->id_link;
$this->params['breadcrumbs'][] = ['label' => 'Ссылки разделов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="nsection-link-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['/nsectionlink/update', 'id' => $model->id_section_link], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['/nsectionlink/delete', 'id' => $model->id_section_link], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id_section_link',
            //'id_section',
            'id_link',
        ],
    ]) ?>

</div>