common/models/NSectionImage.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "n_section_image".
 *
 * @property int $id_section_image
 * @property int $id_section
 * @property int $id_image
 * @property bool $is_on_slider
 * @property bool $is_main
 *
 * @property NImage $image
 * @property NSection $section
 */
class NSectionImage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'n_section_image';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_section'], 'required'],
            [['id_section', 'id_image'], 'default', 'value' => null],
            [['id_section', 'id_image'], 'integer'],
            [['is_on_slider', 'is_main'], 'boolean'],
            [['id_image'], 'exist', 'skipOnError' => true, 'targetClass' => NImage::className(), 'targetAttribute' => ['id_image' => 'id_image']],
            [['id_section'], 'exist', 'skipOnError' => true, 'targetClass' => NSection::className(), 'targetAttribute' => ['id_section' => 'id_section']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_section_image' => 'Код изображения раздела',
            'id_section' => 'Код раздела',
            'id_image' => 'Код изображения',
            'is_on_slider' => 'На слайдере',
            'is_main' => 'Главное изображение',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImage()
    {
        return $this->hasOne(NImage::className(), ['id_image' => 'id_image']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSection()
    {
        return $this->hasOne(NSection::className(), ['id_section' => 'id_section']);
    }

    /**
     * {@inheritdoc}
     * @return NSectionImageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new NSectionImageQuery(get_called_class());
    }
}

backend/controllers/NSectionImageController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\NSectionImage;
use common\models\NSectionImageSearch;
use common\models\NImageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * NSectionImageController implements the CRUD actions for NSectionImage model.
 */
class NsectionimageController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    // Здесь запрет перехода на страницу не автоизованному пользователю. 
                    [
                        'allow' => false,
                        'roles' => ['?']
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all NSectionImage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NSectionImageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single NSectionImage model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new NSectionImage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NSectionImage();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_section_image]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing NSectionImage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $searchModelNImage = new NImageSearch();
        $dataProviderNImage = $searchModelNImage->search(Yii::$app->request->queryParams+['NImageSearch' => ['==', 'id_image' =>$id]]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_section_image]);
        }

        return $this->render('update', [
            'model' => $model,
            'dataProviderNImage' => $dataProviderNImage,
        ]);
    }

    /**
     * Deletes an existing NSectionImage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the NSectionImage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NSectionImage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NSectionImage::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/nsectionimage/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionImage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nsection-image-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_section')->textInput() ?>

    <?= $form->field($model, 'id_image')->textInput() ?>

    <?= $form->field($model, 'is_on_slider')->checkbox() ?>

    <?= $form->field($model, 'is_main')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

 <!--  --------------- Картинки -------------- -->

    <?= ListView::widget([
            'dataProvider' => $dataProviderNImage,
            'summary' => false,
            'itemView'=> function ($model , $key , $index , $widget) {
                return $this->render('/nimage/update',[
                'model' => $model,
                ]);
            }
    ]) ?>    

</div>

backend/views/nsectionimage/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionImageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nsection-image-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id_section_image') ?>

    <?= $form->field($model, 'id_section') ?>

    <?= $form->field($model, 'id_image') ?>

    <?= $form->field($model, 'is_on_slider')->checkbox() ?>

    <?= $form->field($model, 'is_main')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/nsectionimage/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionImage */

$this->title = 'Добавить изображение разделов';
$this->params['breadcrumbs'][] = ['label' => 'Изображения разделов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nsection-image-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/nsectionimage/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\NSectionImageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Изображения разделов';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nsection-image-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить изображения разделов', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_section_image',
            'id_section',
            'id_image',
            'is_on_slider:boolean',
            'is_main:boolean',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/nsectionimage/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionImage */

$this->title = 'Редактировать изображения разделов: ' . $model->id_section_image;
$this->params['breadcrumbs'][] = ['label' => 'Изображения разделов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_section_image, 'url' => ['view', 'id' => $model->id_section_image]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="nsection-image-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'dataProviderNImage' => $dataProviderNImage,
    ]) ?>

</div>

backend/views/nsectionimage/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\NSectionImage */

$this->title = 'Изображение №' . $model->id_section_image;
$this->params['breadcrumbs'][] = ['label' => 'Изображения разделов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="nsection-image-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['/nsectionimage/update', 'id' => $model->id_section_image], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['/nsectionimage/delete', 'id' => $model->id_section_image], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id_section_image',
            //'id_section',
            'id_image',
            'is_on_slider:boolean',
            'is_main:boolean',
        ],
    ]) ?>

</div>